#!/bin/bash
# -----------------------------------------------------------
# writes fun bytes to a device
# usage: shoopwhoop /dev/sdb
# -----------------------------------------------------------

if [[ -z "${1}" || (( ! -b "${1}" && ! -c "${1}" )) ]]; then
    echo "Usage: $0 <device>"
    exit 9001
fi

trolol="TR"$(printf "OL%.0s" {0..254})
yes "${trolol}" | tr -d "\n" | dd of="${1}" bs=64k status=noxfer 2> /dev/null
exit 0
